#!/bin/bash

SUBDIRECTORY_OK=yes
. "$(git --exec-path)/git-sh-setup"

grok_diff='s:^--- \(a/\)*\(.*\):--- \2:p  ; s/^@@ -\([0-9]*\),\([0-9]*\).*/\1 \2/p'

function fixup_candidates_blame () {
    git diff --cached -U0 | sed -n "$grok_diff" | (
        file=''
        while read offs len; do
            if test "$offs" == '---'; then
                file="$len"
            else
                if test "$len" != '0'; then
                    if test "$file" != '/dev/null'; then
                        git blame -sl -L "$offs,+$len" HEAD -- "$file"
                    fi
                fi
            fi
        done
    ) | cut -d' ' -f 1 | sort -u
}

if test $# -eq 1; then
    git rev-parse --verify "$1" > /dev/null || exit 1
    git commit -m "fixup! $1";
    exit 0
fi


cd_to_toplevel
fixup_candidates_blame | while read sha; do
    print_sha $sha [BLM]
done
